### PR TITLE
feat(config): Set no-debug option in CLI consumer config

### PR DESCRIPTION
**Pull request by astalker**
Note: I've not functionally tested this yet. Doesn't seem like there would be any risk though.

### CODE REVIEW

**Comment by astalker** [comment]
Will fix the tests

**Comment by gsdevme** [comment]
Be good if we could only do this if `kernel.debug === false` though.. ? but perhaps not required.

**Comment by astalker** [comment]
Probably not required for now. I agree that we could review this a bit further to try and get it to one place where we set this. We just need to understand the limitations, like the env var etc.

Lets see if this helps

**Comment by astalker** [comment]
Ta @gsdevme

**Pull request merged**
