### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by volkan**
added prefetch_count for multiple consumer.

https://www.rabbitmq.com/consumer-prefetch.html

### CODE REVIEW

**Comment by shieldo** [comment]
@volkan Can you make the spacing inside the braces match the other lines?

@calumbrodie Is this good for a merge?

**Comment by gsdevme** [comment]
The addition is an option in a third party bundle though, it's not that relevant to this exact bundle.

**Comment by volkan** [comment]
@shieldo done and I updated my previous message.

**Comment by calumbrodie** [comment]
Hi @volkan If you looks at the dependency injection configuration https://github.com/usemarkup/JobQueueBundle/blob/master/DependencyInjection/Configuration.php

You can see this is already an option. This option is being picked up and used by both consumer implementations.

 GO: https://github.com/usemarkup/JobQueueBundle/blob/master/Service/CliConsumerConfigFileWriter.php

PHP:
https://github.com/usemarkup/JobQueueBundle/blob/master/Service/SupervisordConfigFileWriter.php#L197

I think this is a better way to do it that the above?

**Comment by volkan** [comment]
@calumbrodie I think this config (prefetch_count) should be in readme.md. But you know...

**Comment by calumbrodie** [comment]
I've updated the readme

**Pull request closed without merging**
