### PR TITLE
use 1.7.x versions of oldsound/rabbitmq-bundle

### PR DESCRIPTION
**Pull request by shieldo**

### CODE REVIEW

**Comment by shieldo** [comment]
bump

**Comment by shieldo** [comment]
@calumbrodie bump (needed for updating mogul)

**Comment by calumbrodie** [comment]
@shieldo Mogul doesn't use rabbitmq, it's pegged to a version of this bundle that still uses resque. When updating mogul - don't bump this bundle (the infrastructure is not in place to support it on the media servers at this time (involves installing rabbitMQ and changing application to provide rabbitMQ configuration etc.)

**Comment by shieldo** [comment]
@calumbrodie Can this be merged anyway so long as Mogul is still pegged to a prior version?

**Comment by shieldo** [comment]
(Mogul should be updated separately of course, but there's no reason to specify a dev version of this particular package anymore)

**Pull request closed without merging**
