### PR TITLE
chore: drop symfony v2

### PR DESCRIPTION
**Pull request by gsdevme**
This drops Symfony v2 from the dependencies.

### CODE REVIEW

**Comment by shieldo** [comment]
What's the reasoning behind dropping v2 support? (It's probably OK if we increment the release version.)

**Comment by gsdevme** [comment]
To reduce the burden of thought when making changes. After this 2.8 and such don't need to be taken into account when making changes.

Composer will handle anyone who can't upgrade to 3 and/or Im happy to tag a major release if that helps as a clear cut off point. The rate of change in this bundle is fairly low so I don't see much advantage is having a bigger pitch to play on when making changes

**Comment by shieldo** [comment]
There's no difference though in the burden of thought in supporting v2.8 versus v3.0+ - it's the same API.

**Comment by gsdevme** [comment]
Will re PR dropping everything < 3.4

**Pull request closed without merging**
