### PR TITLE
fix(repository): catch exception if missing job log

### PR DESCRIPTION
**Pull request by redjam13**

### CODE REVIEW

**Comment by NeilMasters** [comment]
@calumbrodie this looks relatively straight forward - can you take a peek at this as I would really like to get it deployed.

**Comment by redjam13** [comment]
@NeilMasters I think @calumbrodie is soon going to rework this to swap out Redis for MySQL to store the logs anyway so maybe it's not worth.

**Comment by NeilMasters** [comment]
@redjam13 I was aware of that but it would get the job functionality at least usable again on UK.

**Comment by gsdevme** [comment]
I would say this looks good! we should merge

**Pull request merged**
